event_manager/event_manager/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

event_manager/event_manager_app/models.py
from django.db import models

# Create your models here.

class Event(models.Model):
    eventName = models.CharField(max_length=32)
    description = models.TextField()
    location = models.CharField(max_length=32)
    startDate = models.DateField(default=None)
    startTime = models.TimeField(default=None)
    endDate = models.DateField(default=None)
    endTime = models.TimeField(default=None)
    registerbyDate = models.DateField(default=None)
    registerbyTime = models.TimeField(default=None)
    hostEmail = models.EmailField(default=None)
    hostpwd = models.CharField(max_length=15)

    def __str__(self) -> str:
        return str(self.id) + " : " + self.eventName

class Participant(models.Model):
    name = models.CharField(max_length=20)
    contact = models.CharField(max_length=15)
    email = models.EmailField()
    event = models.ForeignKey(Event, on_delete=models.CASCADE, default=None)
    registerType = models.CharField(max_length=12, default=None)
    participantCount = models.IntegerField(default=1)

    def __str__(self) -> str:
        return str(self.id) + " : " + self.name  

event_manager/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <head>
        
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                <strong>Message: </strong> {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
            
        </div>
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <title>
            {% block title %}
            {% endblock %}
        </title>
        <h1>
        {% block heading %}
        {% endblock %}
        </h1>
        {% block head %}
        {% endblock %}
        <br> <hr> <br>
    </head>  

    <body {% block body_specifications %}{% endblock %} >
        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        
        {% block body_outsideForm %}
        {% endblock %}
        
        <form {% block actionMethod %}{% endblock %}  > 
            {% csrf_token %}
            {% block body_insideForm %}
            {% endblock %}
        </form>
    
    </body>
</html>

event_manager/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Event Dashboard
{% endblock %}

{% block heading %}
    Event Dashboard
{% endblock %}

{% block head %}
    <script src="{% static '/js/dashBoard.js' %}"></script>
{% endblock %}

{% block actionMethod %}
    name="getEventInfo" action = "{% url 'getEventInfo' %}" onsubmit="return validateForm()" method = "POST"
{% endblock %}

{% block body_outsideForm %}

    <h1>Upcoming Events:</h1><br><br>

    {% for event in events %}
        <h3>
            event-ID : {{event.id}} <br>
            event Name : {{event.eventName}} <br>
            From : {{event.startDate}} {{event.startTime}} &nbsp;&nbsp; To : {{event.endDate}} {{event.endTime}} <br>
            Register By : {{event.registerbyDate}} {{event.registerbyTime}} <br>
            <hr>
        </h3>
    {% endfor %}
    
    <br><br>

{% endblock %}

{% block body_insideForm %}

    <br><br>
    <label for="eventID">Event-ID: </label><br>
    <input type="number" name="eventID" id="eventID" min=0 placeholder="ID of Created Event"> <br><br>
    <label for="hostPwd">Host-Password: </label><br>
    <input type="password" name="eventPassword" id="hostPwd" placeholder="Password"> <br><br>

    <input type="submit" id="Submit">

    <h5> <a href = "{% url 'index' %}"> back to index </a> </h5>
    <br><br>

{% endblock %}

event_manager/templates/eventInfo.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Event Info
{% endblock %}

{% block heading %}
    Event Info
{% endblock %}

{% block head %}
    <style>
        table, th, td{
            border: 1px solid black;
        }
    </style>
{% endblock %}

{% block body_outsideForm %}
    <b>Event Name: </b>{{event.eventName}} <br>
    <b>Description: </b>{{event.description}} <br>
    <b>Location: </b>{{event.location}} <br>
    <b>Event Duration: </b>{{event.startDate}} {{event.startTime}} to {{event.endDate}} {{event.endTime}} <br>
    <b>Register By: </b>{{event.registerbyDate}} {{event.registerbyTime}} <br>
    <br><br>
{% endblock %}

{% block body_insideForm %}
    
<br><br>
{% if error_name != 'No Error' %}
    <h1>{{error_name}}</h1>
{% elif event == None %}
    <h1>No Event Found!!</h1>
{% elif event == 'incorrect Password!!' %}
    <h1>{{event}}</h1>
{% else %}
    <table style="width: 100%;">
            <tr>
                <td><b>ID</b></td>
                <td><b>Name</b></td>
                <td><b>Contact</b></td>
                <td><b>Email</b></td>
                <td><b>Registration Type</b></td>
                <td><b>Participant Count</b></td>
            </tr>
        {% for participant in event.participant_set.all %}
            <tr>
                <td>{{participant.id}}</td>
                <td>{{participant.name}}</td>
                <td>{{participant.contact}}</td>
                <td>{{participant.email}}</td>
                <td>{{participant.registerType}}</td>
                <td>{{participant.participantCount}}</td>
            </tr>
        {% endfor %}
    </table>
{% endif %}
<br><br>
<h5> <a href = "{% url 'dashboard' %}"> back to dashboard </a> </h5>
<br><br>

{% endblock %}

event_manager/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Event Management Web App
{% endblock %}

{% block heading %}
    Event Management Web App
{% endblock %}

{% block body_outsideForm %}
    <a href = "{% url 'organize' %}"> <h2>Organize Event</h2> </a>
    <br>
    <a href = "{% url 'register' %}"> <h2>Register in Event</h2> </a>
    <br>
    <a href = "{% url 'dashboard' %}"> <h2>Dashboard</h2> </a>
    <br>
{% endblock %}

event_manager/templates/organizeEvent.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Organize an Event
{% endblock %}

{% block heading %}
    Organize an Event
{% endblock %}

{% block head %}
    <script src="{% static '/js/organizeEvent.js' %}"></script>
{% endblock %}

{% block body_outsideForm %}
{% endblock %}

{% block actionMethod %}
    name="organizeEventForm" action = "{% url 'newEvent' %}" onsubmit="return validateForm()" method = "POST" re
{% endblock %}

{% block body_insideForm %}
    {% csrf_token %}
    <br><br>
    <label for="eName">Event Name: </label><br>
    <input type="text" name="event_name" id="eName" placeholder="name of the event"> <br><br>
    
    <label for="descr">Description: </label><br>
    <textarea name="description" id="descr" placeholder="Describe the event"></textarea><br><br>
    
    <label for="loc">Location: </label><br>
    <input type="text" name="location"id="loc" placeholder="location of the event"> <br><br>

    <label for="sDate"> From: </label>
    <input type="date" name="startDate" id="sDate">
    <input type="time" name="startTime" id="sTime"><br>
    <label for="eDate"> &nbsp;&nbsp;&nbsp;&nbsp; To: </label>
    <input type="date" name="endDate" id="eDate">
    <input type="time" name="endTime" id="eTime"> <br><br>

    <label for="registerD">Register By: </label>
    <input type="date" name="registerByDate" id="registerD">
    <input type="time" name="registerByTime" id="registerT"> <br><br>

    <label for="hmail">Host Email: </label><br>
    <input type="email" name="hostEmail" id="hmail" placeholder="Email-ID"> <br><br>
    <label for="hostPwd">Host Password: </label><br>
    <input type="password" name="hostPwd" id="hostPwd" placeholder="Password"> <br><br>

    <input type="submit" id="submit" ><br><br>
    <input type='reset'>

    <br><br>
    <h5> <a href = "{% url 'index' %}"> back to index </a> </h5>
    <br><br>
    
{% endblock %}

event_manager/templates/registerEvent.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Register in an Event
{% endblock %}

{% block heading %}
    Register in an Event
{% endblock %}

{% block head %}
    <script src="{% static '/js/registerEvent.js' %}"></script>
{% endblock %}


{% block body_outsideForm %}

    <br>
    <h2><u>Events Available For Registration: </u></h2><br>
    {% if Events is not None %}
        {% for event in Events %}
            <h2>{{ event.eventName }}</h2>
            <h3>
                Description: {{ event.description }} <br>
                Starts From:  {{ event.startDate }}, {{ event.startTime }} <br>
                Ends On:  {{ event.endDate }}, {{ event.endTime }} <br>
                Register By:  {{ event.registerbyDate }}, {{ event.registerbyTime }} <br>
                Venue:  {{ event.location }} <br><hr>
            </h3>
        {% endfor %}
    {% endif %}
    
{% endblock %}

{% block actionMethod %}
    name="newParticipantForm" action = "{% url 'newParticipant' %}" onsubmit="return validateForm()" method = "POST"
{% endblock %}

{% block body_insideForm %}
    {% csrf_token %}
    <br><br>

    {% if Events is None %}
        
        <h2>No Events To Participate !!</h2><br>
        <h4>There are no events hosted currently or in the coming future. Try again later.</h4>

    {% else %}

        <label for="name">Name: </label>
        <input type="text" name="name" id="name" placeholder="Enter your name"> <br><br>
        <label for="contactNum">Contact Number: </label>
        <input type="tel" name="contactNum" id="contactNum" placeholder="Mobile Number with Country Code"> <br><br>
        
        <label for="emailID">Email ID: </label>
        <input type="email" name="emailID" id="emailID" placeholder="Email-ID"> <br><br>

        <label>Select Event:</label><br>

        {% for event in Events %}
            <input type="radio" id="{{event.id}}" name="Event" value="{{event.id}}">
            <label for="{{event.id}}"> {{event.eventName}} </label>
        {% endfor %}
        <br><br>

        <label>Registration Type: </label>           
        <input type="radio" onclick="hideParticipantCount()" id="Individual" name="registerType" value="Individual">
        <label for="Individual">Individual</label> &nbsp; &nbsp;

        <input type="radio" onclick="showParticipantCount();" id="Group" name="registerType" value="Group">
        <label for="Group">Group</label> &nbsp; &nbsp; <br><br>
        
        <div id="if_Group" style="visibility: hidden;">
            <label>Number of Participants: </label>
            <input type="number" name="participantCount" id="participantCount" min=1 max=10 placeholder="Group Members Count"> <br><br>
        </div>

        <input type="submit" id="submit">
        
    {% endif %}

    <h5> <a href = "{% url 'index' %}"> back to index </a> </h5>
    <br><br>

{% endblock %}